# Generated by Django 4.2.10 on 2024-03-16 02:00

from django.db import migrations, models
import shortuuid.django_fields


class Migration(migrations.Migration):

    dependencies = [
        ('djsci', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LocalNotebook',
            fields=[
                ('id', shortuuid.django_fields.ShortUUIDField(alphabet=None, length=22, max_length=22, prefix='', primary_key=True, serialize=False)),
                ('notebook', models.FileField(blank=True, default=None, null=True, upload_to='local_notebooks')),
            ],
        ),
    ]
