# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'GUI.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from icon import icon_rc

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(987, 794)
        MainWindow.setStyleSheet("background:transparent;")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.frame_7 = QtWidgets.QFrame(self.centralwidget)
        self.frame_7.setObjectName("frame_7")
        self.label_19 = QtWidgets.QLabel(self.frame_7)
        self.label_19.setGeometry(QtCore.QRect(0, 730, 961, 31))
        self.label_19.setStyleSheet("background-color:rgba(2,2,2,150);")
        self.label_19.setText("")
        self.label_19.setObjectName("label_19")
        self.label = QtWidgets.QLabel(self.frame_7)
        self.label.setGeometry(QtCore.QRect(1, 1, 961, 761))
        self.label.setStyleSheet("border-radius:50px;\n"
"opacity:0.5;")
        self.label.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label.setFrameShadow(QtWidgets.QFrame.Plain)
        self.label.setText("")
        self.label.setTextFormat(QtCore.Qt.AutoText)
        self.label.setPixmap(QtGui.QPixmap("./icon/background-43-6.png"))
        self.label.setScaledContents(False)
        self.label.setObjectName("label")
        self.tabWidget = QtWidgets.QTabWidget(self.frame_7)
        self.tabWidget.setGeometry(QtCore.QRect(0, 0, 961, 731))
        self.tabWidget.setMaximumSize(QtCore.QSize(166660, 166660))
        self.tabWidget.setToolTipDuration(-1)
        self.tabWidget.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.tabWidget.setAutoFillBackground(False)
        self.tabWidget.setStyleSheet("QTabWidget::pane { /* The tab widget frame */\n"
"    border-top: 2px solid #C2C7CB;\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, stop:0 rgba(128, 218, 205, 255), stop:1 rgba(44, 175, 255, 158))\n"
"}\n"
"\n"
"\n"
"\n"
"QTabWidget::tab-bar {\n"
"\n"
"    width:342px\n"
"}\n"
"\n"
"QTabBar::tab {\n"
"\n"
"min-width:70px;\n"
"\n"
"min-height:25px;\n"
"\n"
"color: white;\n"
"\n"
"font:13px \"Microsoft YaHei\";\n"
"\n"
"border: 2px solid;\n"
"\n"
"border-color:rgb(0, 0, 120);\n"
"\n"
"border-radius:3px;\n"
"}\n"
"\n"
"QTabBar::tab:selected{\n"
"\n"
"min-width:70px;\n"
"\n"
"min-height:25px;\n"
"color: white;\n"
"\n"
"font:13px \"Microsoft YaHei\";\n"
"\n"
"border: 2px solid;\n"
"\n"
"border-bottom: 0px solid;\n"
"\n"
"border-color: #4796f0;\n"
"}\n"
"\n"
"")
        self.tabWidget.setTabPosition(QtWidgets.QTabWidget.North)
        self.tabWidget.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.tabWidget.setElideMode(QtCore.Qt.ElideNone)
        self.tabWidget.setUsesScrollButtons(True)
        self.tabWidget.setDocumentMode(False)
        self.tabWidget.setTabsClosable(False)
        self.tabWidget.setMovable(False)
        self.tabWidget.setTabBarAutoHide(False)
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.layoutWidget = QtWidgets.QWidget(self.tab)
        self.layoutWidget.setGeometry(QtCore.QRect(200, 100, 691, 41))
        self.layoutWidget.setObjectName("layoutWidget")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setSpacing(100)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_2 = QtWidgets.QLabel(self.layoutWidget)
        self.label_2.setStyleSheet("color:rgb(0, 0, 0);\n"
"font: 18pt ;\n"
"font: 18pt \"华文新魏\";\n"
"font: 75 18pt \"Adobe Gothic Std B\";\n"
"")
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_2.addWidget(self.label_2)
        self.label_3 = QtWidgets.QLabel(self.layoutWidget)
        self.label_3.setStyleSheet("color:rgb(0, 0, 0);\n"
";\n"
"font: 75 18pt \"Adobe Gothic Std B\";")
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_2.addWidget(self.label_3)
        self.layoutWidget1 = QtWidgets.QWidget(self.tab)
        self.layoutWidget1.setGeometry(QtCore.QRect(200, 170, 691, 301))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.layoutWidget1)
        self.horizontalLayout.setContentsMargins(10, 10, 10, 10)
        self.horizontalLayout.setSpacing(100)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.frame = QtWidgets.QFrame(self.layoutWidget1)
        self.frame.setStyleSheet("background-color:rgb(255, 255, 255);\n"
"border:1px outset black;")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.horizontalLayout.addWidget(self.frame)
        self.frame_2 = QtWidgets.QFrame(self.layoutWidget1)
        self.frame_2.setStyleSheet("background-color:rgb(255, 255, 255);\n"
"border:1px outset black;")
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.horizontalLayout.addWidget(self.frame_2)
        self.layoutWidget2 = QtWidgets.QWidget(self.tab)
        self.layoutWidget2.setGeometry(QtCore.QRect(200, 490, 691, 41))
        self.layoutWidget2.setObjectName("layoutWidget2")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.layoutWidget2)
        self.horizontalLayout_3.setContentsMargins(10, 0, 10, 0)
        self.horizontalLayout_3.setSpacing(100)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.horizontalScrollBar_2 = QtWidgets.QScrollBar(self.layoutWidget2)
        self.horizontalScrollBar_2.setStyleSheet("QScrollBar:horizontal {\n"
"    border: 2px solid qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, stop:0 rgba(8, 123, 202, 255), stop:1 rgba(255, 255, 255, 255));\n"
"    background: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, stop:0 rgba(8, 123, 202, 255), stop:1 rgba(255, 255, 255, 255));\n"
"    height: 15px;\n"
"    margin: 0px 20px 0 20px;\n"
"}\n"
"QScrollBar::handle:horizontal {\n"
"    background:rgba(79, 253, 255, 150);\n"
"    min-width: 20px;\n"
"    margin-left:3px;\n"
"    margin-right:3px;\n"
"    border:0.5px solid;\n"
"    border-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, stop:0 rgba(8, 123, 202, 255), stop:1 rgba(255, 255, 255, 255));\n"
"}\n"
"QScrollBar::add-line:horizontal {\n"
"    border: 2px solid qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, stop:0 rgba(8, 123, 202, 255), stop:1 rgba(255, 255, 255, 255));;\n"
"    background:qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, stop:0 rgba(8, 123, 202, 255), stop:1 rgba(255, 255, 255, 255));\n"
"    \n"
"    width: 20px;\n"
"    subcontrol-position: right;\n"
"    subcontrol-origin: margin;\n"
"}\n"
"\n"
"QScrollBar::sub-line:horizontal {\n"
"    border: 2px solid qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, stop:0 rgba(8, 123, 202, 255), stop:1 rgba(255, 255, 255, 255));;\n"
"    background: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, stop:0 rgba(8, 123, 202, 255), stop:1 rgba(255, 255, 255, 255));\n"
"    width: 20px;\n"
"    subcontrol-position: left;\n"
"    subcontrol-origin: margin;\n"
"}\n"
"QScrollBar:left-arrow:horizontal, QScrollBar::right-arrow:horizontal {\n"
"    border: 2px solid grey;\n"
"    width: 3px;\n"
"    height: 3px;\n"
"    background: white;\n"
"}\n"
"\n"
"QScrollBar::add-page:horizontal, QScrollBar::sub-page:horizontal {\n"
"    background: none;\n"
"}")
        self.horizontalScrollBar_2.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalScrollBar_2.setObjectName("horizontalScrollBar_2")
        self.horizontalLayout_3.addWidget(self.horizontalScrollBar_2)
        self.horizontalScrollBar = QtWidgets.QScrollBar(self.layoutWidget2)
        self.horizontalScrollBar.setStyleSheet("QScrollBar:horizontal {\n"
"    border: 2px solid qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, stop:0 rgba(8, 123, 202, 255), stop:1 rgba(255, 255, 255, 255));\n"
"    background: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, stop:0 rgba(8, 123, 202, 255), stop:1 rgba(255, 255, 255, 255));\n"
"    height: 15px;\n"
"    margin: 0px 20px 0 20px;\n"
"}\n"
"QScrollBar::handle:horizontal {\n"
"    background:rgba(79, 253, 255, 150);\n"
"    min-width: 20px;\n"
"    margin-left:3px;\n"
"    margin-right:3px;\n"
"    border:0.5px solid;\n"
"    border-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, stop:0 rgba(8, 123, 202, 255), stop:1 rgba(255, 255, 255, 255));\n"
"}\n"
"QScrollBar::add-line:horizontal {\n"
"    border: 2px solid qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, stop:0 rgba(8, 123, 202, 255), stop:1 rgba(255, 255, 255, 255));;\n"
"    background:qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, stop:0 rgba(8, 123, 202, 255), stop:1 rgba(255, 255, 255, 255));\n"
"    \n"
"    width: 20px;\n"
"    subcontrol-position: right;\n"
"    subcontrol-origin: margin;\n"
"}\n"
"\n"
"QScrollBar::sub-line:horizontal {\n"
"    border: 2px solid qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, stop:0 rgba(8, 123, 202, 255), stop:1 rgba(255, 255, 255, 255));;\n"
"    background: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, stop:0 rgba(8, 123, 202, 255), stop:1 rgba(255, 255, 255, 255));\n"
"    width: 20px;\n"
"    subcontrol-position: left;\n"
"    subcontrol-origin: margin;\n"
"}\n"
"QScrollBar:left-arrow:horizontal, QScrollBar::right-arrow:horizontal {\n"
"    border: 2px solid grey;\n"
"    width: 3px;\n"
"    height: 3px;\n"
"    background: white;\n"
"}\n"
"\n"
"QScrollBar::add-page:horizontal, QScrollBar::sub-page:horizontal {\n"
"    background: none;\n"
"}")
        self.horizontalScrollBar.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalScrollBar.setObjectName("horizontalScrollBar")
        self.horizontalLayout_3.addWidget(self.horizontalScrollBar)
        self.frame_3 = QtWidgets.QFrame(self.tab)
        self.frame_3.setGeometry(QtCore.QRect(0, 0, 171, 701))
        self.frame_3.setStyleSheet("background-color:rgba(220, 220, 220, 120);\n"
"border-right:2px solid;\n"
"border-right-color:qradialgradient(spread:repeat, cx:0.5, cy:0.5, radius:0.077, fx:0.5, fy:0.5, stop:0 rgba(0, 169, 255, 147), stop:0.497326 rgba(0, 0, 0, 147), stop:1 rgba(0, 169, 255, 147));\n"
"\n"
"\n"
"")
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.lineEdit_4 = QtWidgets.QLineEdit(self.frame_3)
        self.lineEdit_4.setGeometry(QtCore.QRect(30, 290, 113, 20))
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.label_7 = QtWidgets.QLabel(self.frame_3)
        self.label_7.setGeometry(QtCore.QRect(40, 260, 81, 16))
        self.label_7.setStyleSheet("background:transparent;\n"
"border:none;\n"
"font: 9pt \"微软雅黑\";")
        self.label_7.setAlignment(QtCore.Qt.AlignCenter)
        self.label_7.setObjectName("label_7")
        self.lineEdit_3 = QtWidgets.QLineEdit(self.frame_3)
        self.lineEdit_3.setGeometry(QtCore.QRect(30, 220, 113, 20))
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.label_4 = QtWidgets.QLabel(self.frame_3)
        self.label_4.setGeometry(QtCore.QRect(20, 180, 131, 20))
        self.label_4.setStyleSheet("background:transparent;\n"
"border:none;\n"
"font: 9pt \"微软雅黑\";")
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.lineEdit_2 = QtWidgets.QLineEdit(self.frame_3)
        self.lineEdit_2.setGeometry(QtCore.QRect(30, 370, 113, 20))
        self.lineEdit_2.setStyleSheet("background-:transparent")
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.label_6 = QtWidgets.QLabel(self.frame_3)
        self.label_6.setGeometry(QtCore.QRect(40, 330, 91, 20))
        self.label_6.setStyleSheet("background:transparent;\n"
"border:none;\n"
"font: 9pt \"微软雅黑\";")
        self.label_6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_6.setObjectName("label_6")
        self.lineEdit = QtWidgets.QLineEdit(self.frame_3)
        self.lineEdit.setGeometry(QtCore.QRect(30, 450, 113, 20))
        self.lineEdit.setObjectName("lineEdit")
        self.label_5 = QtWidgets.QLabel(self.frame_3)
        self.label_5.setGeometry(QtCore.QRect(30, 410, 111, 16))
        self.label_5.setStyleSheet("background:transparent;\n"
"border:none;\n"
"font: 9pt \"微软雅黑\";")
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName("label_5")
        self.label_8 = QtWidgets.QLabel(self.frame_3)
        self.label_8.setGeometry(QtCore.QRect(30, 120, 111, 20))
        self.label_8.setStyleSheet("font: 75 12pt \"Adobe Gothic Std B\";\n"
"border:None;\n"
"background:transparent;")
        self.label_8.setAlignment(QtCore.Qt.AlignCenter)
        self.label_8.setObjectName("label_8")
        self.pushButton_run_enhance = QtWidgets.QPushButton(self.frame_3)
        self.pushButton_run_enhance.setGeometry(QtCore.QRect(30, 530, 111, 21))
        self.pushButton_run_enhance.setStyleSheet("\n"
"font: 9pt \"微软雅黑\";")
        self.pushButton_run_enhance.setObjectName("pushButton_run_enhance")
        self.pushButton_5 = QtWidgets.QPushButton(self.tab)
        self.pushButton_5.setGeometry(QtCore.QRect(280, 580, 151, 23))
        self.pushButton_5.setStyleSheet("background-color:rgba(220, 220, 220, 200);\n"
"\n"
"\n"
"font: 9pt \"微软雅黑\";")
        self.pushButton_5.setObjectName("pushButton_5")
        self.pushButton_6 = QtWidgets.QPushButton(self.tab)
        self.pushButton_6.setGeometry(QtCore.QRect(670, 580, 131, 23))
        self.pushButton_6.setStyleSheet("background-color:rgba(220, 220, 220, 200);\n"
"\n"
"\n"
"font: 9pt \"微软雅黑\";")
        self.pushButton_6.setObjectName("pushButton_6")
        self.layoutWidget3 = QtWidgets.QWidget(self.tab)
        self.layoutWidget3.setGeometry(QtCore.QRect(200, 460, 691, 20))
        self.layoutWidget3.setObjectName("layoutWidget3")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.layoutWidget3)
        self.horizontalLayout_5.setContentsMargins(10, 0, 10, 0)
        self.horizontalLayout_5.setSpacing(100)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_16 = QtWidgets.QLabel(self.layoutWidget3)
        self.label_16.setStyleSheet("font: 9pt \"微软雅黑\";")
        self.label_16.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_16.setObjectName("label_16")
        self.horizontalLayout_5.addWidget(self.label_16)
        self.label_17 = QtWidgets.QLabel(self.layoutWidget3)
        self.label_17.setStyleSheet("font: 9pt \"微软雅黑\";")
        self.label_17.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_17.setObjectName("label_17")
        self.horizontalLayout_5.addWidget(self.label_17)
        self.layoutWidget.raise_()
        self.frame_3.raise_()
        self.layoutWidget.raise_()
        self.layoutWidget.raise_()
        self.layoutWidget.raise_()
        self.pushButton_5.raise_()
        self.pushButton_6.raise_()
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.frame_4 = QtWidgets.QFrame(self.tab_2)
        self.frame_4.setGeometry(QtCore.QRect(0, 0, 171, 721))
        self.frame_4.setStyleSheet("background-color:rgba(220, 220, 220, 120);\n"
"border-right:2px solid qradialgradient(spread:repeat, cx:0.5, cy:0.5, radius:0.077, fx:0.5, fy:0.5, stop:0 rgba(0, 169, 255, 147), stop:0.497326 rgba(0, 0, 0, 147), stop:1 rgba(0, 169, 255, 147));")
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.label_9 = QtWidgets.QLabel(self.frame_4)
        self.label_9.setGeometry(QtCore.QRect(30, 140, 111, 21))
        self.label_9.setStyleSheet("background:transparent;\n"
"font: 75 12pt \"Adobe Gothic Std B\";\n"
"border:none;")
        self.label_9.setAlignment(QtCore.Qt.AlignCenter)
        self.label_9.setObjectName("label_9")
        self.label_10 = QtWidgets.QLabel(self.frame_4)
        self.label_10.setGeometry(QtCore.QRect(40, 200, 91, 20))
        self.label_10.setStyleSheet("background:transparent;\n"
"border:none;\n"
"font: 9pt \"微软雅黑\";")
        self.label_10.setAlignment(QtCore.Qt.AlignCenter)
        self.label_10.setObjectName("label_10")
        self.lineEdit_5 = QtWidgets.QLineEdit(self.frame_4)
        self.lineEdit_5.setGeometry(QtCore.QRect(28, 238, 119, 20))
        self.lineEdit_5.setObjectName("lineEdit_5")
        self.label_11 = QtWidgets.QLabel(self.frame_4)
        self.label_11.setGeometry(QtCore.QRect(37, 270, 108, 17))
        self.label_11.setStyleSheet("background:transparent;\n"
"border:none;\n"
"font: 9pt \"微软雅黑\";")
        self.label_11.setAlignment(QtCore.Qt.AlignCenter)
        self.label_11.setObjectName("label_11")
        self.lineEdit_6 = QtWidgets.QLineEdit(self.frame_4)
        self.lineEdit_6.setGeometry(QtCore.QRect(28, 304, 119, 20))
        self.lineEdit_6.setObjectName("lineEdit_6")
        self.label_13 = QtWidgets.QLabel(self.frame_4)
        self.label_13.setGeometry(QtCore.QRect(27, 350, 121, 17))
        self.label_13.setStyleSheet("background:transparent;\n"
"border:none;\n"
"font: 9pt \"微软雅黑\";")
        self.label_13.setAlignment(QtCore.Qt.AlignCenter)
        self.label_13.setObjectName("label_13")
        self.comboBox = QtWidgets.QComboBox(self.frame_4)
        self.comboBox.setGeometry(QtCore.QRect(28, 384, 121, 21))
        self.comboBox.setStyleSheet("font: 9pt \"微软雅黑\";")
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.label_14 = QtWidgets.QLabel(self.frame_4)
        self.label_14.setGeometry(QtCore.QRect(37, 430, 99, 17))
        self.label_14.setStyleSheet("background:transparent;\n"
"border:none;\n"
"font: 9pt \"微软雅黑\";")
        self.label_14.setAlignment(QtCore.Qt.AlignCenter)
        self.label_14.setObjectName("label_14")
        self.comboBox_2 = QtWidgets.QComboBox(self.frame_4)
        self.comboBox_2.setGeometry(QtCore.QRect(28, 464, 121, 21))
        self.comboBox_2.setStyleSheet("font: 9pt \"微软雅黑\";")
        self.comboBox_2.setObjectName("comboBox_2")
        self.comboBox_2.addItem("")
        self.frame_5 = QtWidgets.QFrame(self.tab_2)
        self.frame_5.setGeometry(QtCore.QRect(170, 0, 311, 311))
        self.frame_5.setStyleSheet("background-color:white;\n"
"border:1px solid black;\n"
"border-left:none;\n"
"margin-left:1px;")
        self.frame_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.frame_6 = QtWidgets.QFrame(self.tab_2)
        self.frame_6.setGeometry(QtCore.QRect(650, 0, 311, 311))
        self.frame_6.setStyleSheet("background-color:white;\n"
"border:1px solid black")
        self.frame_6.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_6.setObjectName("frame_6")
        self.frame_8 = QtWidgets.QFrame(self.tab_2)
        self.frame_8.setGeometry(QtCore.QRect(170, 390, 311, 311))
        self.frame_8.setStyleSheet("background-color:white;\n"
"border:1px solid black;\n"
"border-left:none;\n"
"margin-left:1px")
        self.frame_8.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_8.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_8.setObjectName("frame_8")
        self.frame_9 = QtWidgets.QFrame(self.tab_2)
        self.frame_9.setGeometry(QtCore.QRect(650, 390, 311, 311))
        self.frame_9.setStyleSheet("background-color:white;\n"
"border:1px solid black")
        self.frame_9.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_9.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_9.setObjectName("frame_9")
        self.pushButton_11 = QtWidgets.QPushButton(self.tab_2)
        self.pushButton_11.setGeometry(QtCore.QRect(500, 440, 131, 23))
        self.pushButton_11.setStyleSheet("background-color:rgba(220, 220, 220, 200);\n"
"\n"
"\n"
"font: 9pt \"微软雅黑\";")
        self.pushButton_11.setObjectName("pushButton_11")
        self.pushButton_12 = QtWidgets.QPushButton(self.tab_2)
        self.pushButton_12.setGeometry(QtCore.QRect(500, 490, 131, 23))
        self.pushButton_12.setStyleSheet("background-color:rgba(220, 220, 220, 200);\n"
"\n"
"\n"
"font: 9pt \"微软雅黑\";")
        self.pushButton_12.setObjectName("pushButton_12")
        self.pushButton_13 = QtWidgets.QPushButton(self.tab_2)
        self.pushButton_13.setGeometry(QtCore.QRect(500, 540, 131, 23))
        self.pushButton_13.setStyleSheet("background-color:rgba(220, 220, 220, 200);\n"
"\n"
"\n"
"font: 9pt \"微软雅黑\";")
        self.pushButton_13.setObjectName("pushButton_13")
        self.pushButton_14 = QtWidgets.QPushButton(self.tab_2)
        self.pushButton_14.setGeometry(QtCore.QRect(500, 590, 131, 23))
        self.pushButton_14.setStyleSheet("background-color:rgba(220, 220, 220, 200);\n"
"\n"
"\n"
"font: 9pt \"微软雅黑\";")
        self.pushButton_14.setObjectName("pushButton_14")
        self.pushButton_15 = QtWidgets.QPushButton(self.tab_2)
        self.pushButton_15.setGeometry(QtCore.QRect(500, 640, 131, 23))
        self.pushButton_15.setStyleSheet("background-color:rgba(220, 220, 220, 200);\n"
"\n"
"\n"
"font: 9pt \"微软雅黑\";")
        self.pushButton_15.setObjectName("pushButton_15")
        self.frame_10 = QtWidgets.QFrame(self.tab_2)
        self.frame_10.setGeometry(QtCore.QRect(479, -1, 171, 311))
        self.frame_10.setStyleSheet("background-color:rgba(220, 220, 220, 120);")
        self.frame_10.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_10.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_10.setObjectName("frame_10")
        self.label_12 = QtWidgets.QLabel(self.frame_10)
        self.label_12.setGeometry(QtCore.QRect(60, 20, 54, 20))
        self.label_12.setStyleSheet("font: 75 12pt \"Adobe Gothic Std B\";\n"
"background:transparent")
        self.label_12.setAlignment(QtCore.Qt.AlignCenter)
        self.label_12.setObjectName("label_12")
        self.pushButton_16 = QtWidgets.QPushButton(self.frame_10)
        self.pushButton_16.setGeometry(QtCore.QRect(21, 250, 131, 23))
        self.pushButton_16.setStyleSheet("background-color:rgba(220, 220, 220, 200);\n"
"\n"
"\n"
"font: 9pt \"微软雅黑\";")
        self.pushButton_16.setObjectName("pushButton_16")
        self.pushButton_8 = QtWidgets.QPushButton(self.frame_10)
        self.pushButton_8.setGeometry(QtCore.QRect(21, 151, 131, 23))
        self.pushButton_8.setStyleSheet("background-color:rgba(220, 220, 220, 200);\n"
"\n"
"\n"
"font: 9pt \"微软雅黑\";")
        self.pushButton_8.setObjectName("pushButton_8")
        self.pushButton_7 = QtWidgets.QPushButton(self.frame_10)
        self.pushButton_7.setGeometry(QtCore.QRect(21, 51, 131, 23))
        self.pushButton_7.setStyleSheet("background-color:rgba(220, 220, 220, 200);\n"
"\n"
"\n"
"font: 9pt \"微软雅黑\";")
        self.pushButton_7.setObjectName("pushButton_7")
        self.pushButton_9 = QtWidgets.QPushButton(self.frame_10)
        self.pushButton_9.setGeometry(QtCore.QRect(21, 201, 131, 23))
        self.pushButton_9.setStyleSheet("background-color:rgba(220, 220, 220, 200);\n"
"\n"
"\n"
"font: 9pt \"微软雅黑\";")
        self.pushButton_9.setObjectName("pushButton_9")
        self.pushButton_10 = QtWidgets.QPushButton(self.frame_10)
        self.pushButton_10.setGeometry(QtCore.QRect(21, 101, 131, 23))
        self.pushButton_10.setStyleSheet("background-color:rgba(220, 220, 220, 200);\n"
"\n"
"\n"
"font: 9pt \"微软雅黑\";")
        self.pushButton_10.setObjectName("pushButton_10")
        self.frame_11 = QtWidgets.QFrame(self.tab_2)
        self.frame_11.setGeometry(QtCore.QRect(480, 390, 171, 311))
        self.frame_11.setStyleSheet("background-color:rgba(220, 220, 220, 120);")
        self.frame_11.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_11.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_11.setObjectName("frame_11")
        self.label_15 = QtWidgets.QLabel(self.frame_11)
        self.label_15.setGeometry(QtCore.QRect(60, 20, 54, 20))
        self.label_15.setStyleSheet("font: 75 12pt \"Adobe Gothic Std B\";\n"
"background:transparent")
        self.label_15.setAlignment(QtCore.Qt.AlignCenter)
        self.label_15.setObjectName("label_15")
        self.horizontalScrollBar_3 = QtWidgets.QScrollBar(self.tab_2)
        self.horizontalScrollBar_3.setGeometry(QtCore.QRect(170, 340, 311, 16))
        self.horizontalScrollBar_3.setStyleSheet("QScrollBar:horizontal {\n"
"    border: 2px solid qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, stop:0 rgba(8, 123, 202, 255), stop:1 rgba(255, 255, 255, 255));\n"
"    background: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, stop:0 rgba(8, 123, 202, 255), stop:1 rgba(255, 255, 255, 255));\n"
"    height: 15px;\n"
"    margin: 0px 20px 0 20px;\n"
"}\n"
"QScrollBar::handle:horizontal {\n"
"    background:rgba(79, 253, 255, 150);\n"
"    min-width: 20px;\n"
"    margin-left:3px;\n"
"    margin-right:3px;\n"
"    border:0.5px solid;\n"
"    border-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, stop:0 rgba(8, 123, 202, 255), stop:1 rgba(255, 255, 255, 255));\n"
"}\n"
"QScrollBar::add-line:horizontal {\n"
"    border: 2px solid qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, stop:0 rgba(8, 123, 202, 255), stop:1 rgba(255, 255, 255, 255));;\n"
"    background:qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, stop:0 rgba(8, 123, 202, 255), stop:1 rgba(255, 255, 255, 255));\n"
"    \n"
"    width: 20px;\n"
"    subcontrol-position: right;\n"
"    subcontrol-origin: margin;\n"
"}\n"
"\n"
"QScrollBar::sub-line:horizontal {\n"
"    border: 2px solid qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, stop:0 rgba(8, 123, 202, 255), stop:1 rgba(255, 255, 255, 255));;\n"
"    background: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, stop:0 rgba(8, 123, 202, 255), stop:1 rgba(255, 255, 255, 255));\n"
"    width: 20px;\n"
"    subcontrol-position: left;\n"
"    subcontrol-origin: margin;\n"
"}\n"
"QScrollBar:left-arrow:horizontal, QScrollBar::right-arrow:horizontal {\n"
"    border: 2px solid grey;\n"
"    width: 3px;\n"
"    height: 3px;\n"
"    background: white;\n"
"}\n"
"\n"
"QScrollBar::add-page:horizontal, QScrollBar::sub-page:horizontal {\n"
"    background: none;\n"
"}")
        self.horizontalScrollBar_3.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalScrollBar_3.setObjectName("horizontalScrollBar_3")
        self.label_18 = QtWidgets.QLabel(self.tab_2)
        self.label_18.setGeometry(QtCore.QRect(400, 310, 81, 20))
        self.label_18.setStyleSheet("font: 9pt \"微软雅黑\";")
        self.label_18.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_18.setObjectName("label_18")
        self.frame_4.raise_()
        self.frame_11.raise_()
        self.frame_10.raise_()
        self.frame_5.raise_()
        self.frame_6.raise_()
        self.frame_8.raise_()
        self.frame_9.raise_()
        self.pushButton_11.raise_()
        self.pushButton_12.raise_()
        self.pushButton_13.raise_()
        self.pushButton_14.raise_()
        self.pushButton_15.raise_()
        self.horizontalScrollBar_3.raise_()
        self.label_18.raise_()
        self.tabWidget.addTab(self.tab_2, "")
        self.window_button = QtWidgets.QFrame(self.frame_7)
        self.window_button.setGeometry(QtCore.QRect(810, -10, 151, 41))
        self.window_button.setObjectName("window_button")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.window_button)
        self.horizontalLayout_6.setContentsMargins(0, -1, 6, 0)
        self.horizontalLayout_6.setSpacing(0)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.pushButton_hide = QtWidgets.QPushButton(self.window_button)
        self.pushButton_hide.setStyleSheet("QPushButton {\n"
"background:transparent;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"\n"
"background-color:rgba(127, 127, 127, 150);\n"
"\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"\n"
"border-width:1px;\n"
"border-height:1px;\n"
"\n"
"}")
        self.pushButton_hide.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("./icon/24gl-minus.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_hide.setIcon(icon)
        self.pushButton_hide.setObjectName("pushButton_hide")
        self.horizontalLayout_6.addWidget(self.pushButton_hide)
        self.pushButton_close = QtWidgets.QPushButton(self.window_button)
        self.pushButton_close.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.pushButton_close.setStyleSheet("QPushButton {\n"
"background:transparent;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"\n"
"background-color:rgba(255, 0, 0, 180);\n"
"\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"\n"
"border-width:1px;\n"
"border-height:1px;\n"
"\n"
"}")
        self.pushButton_close.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("./icon/24gl-cross.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_close.setIcon(icon1)
        self.pushButton_close.setObjectName("pushButton_close")
        self.horizontalLayout_6.addWidget(self.pushButton_close)
        self.label.raise_()
        self.label_19.raise_()
        self.tabWidget.raise_()
        self.window_button.raise_()
        self.gridLayout.addWidget(self.frame_7, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(1)
        self.pushButton_hide.clicked.connect(MainWindow.hide) # type: ignore
        self.pushButton_close.clicked.connect(MainWindow.close) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_2.setText(_translate("MainWindow", " Raw Data"))
        self.label_3.setText(_translate("MainWindow", "Enhancement"))
        self.label_7.setText(_translate("MainWindow", "nimg_init"))
        self.label_4.setText(_translate("MainWindow", "smooth_sigma_time"))
        self.label_6.setText(_translate("MainWindow", "maxregshift"))
        self.label_5.setText(_translate("MainWindow", "smooth_sigma"))
        self.label_8.setText(_translate("MainWindow", "Parameters"))
        self.pushButton_run_enhance.setText(_translate("MainWindow", "Run Enhancement"))
        self.pushButton_5.setText(_translate("MainWindow", "load Image(tiff stack)"))
        self.pushButton_6.setText(_translate("MainWindow", "Save Enhacement tif"))
        self.label_16.setText(_translate("MainWindow", "1/6500"))
        self.label_17.setText(_translate("MainWindow", "1/6500"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "Data Enhancement"))
        self.label_9.setText(_translate("MainWindow", "Parameters"))
        self.label_10.setText(_translate("MainWindow", "flow_threshold"))
        self.label_11.setText(_translate("MainWindow", "cellprob_threshold"))
        self.label_13.setText(_translate("MainWindow", "Segmentation model"))
        self.comboBox.setItemText(0, _translate("MainWindow", "cyto"))
        self.comboBox.setItemText(1, _translate("MainWindow", "cyto2"))
        self.label_14.setText(_translate("MainWindow", "Reduction model"))
        self.comboBox_2.setItemText(0, _translate("MainWindow", "3.51Hz_30ms"))
        self.pushButton_11.setText(_translate("MainWindow", "Save Seg tif"))
        self.pushButton_12.setText(_translate("MainWindow", "Save Raw sig"))
        self.pushButton_13.setText(_translate("MainWindow", "Save Reducted sig"))
        self.pushButton_14.setText(_translate("MainWindow", "Save Binarization"))
        self.pushButton_15.setText(_translate("MainWindow", "Save all as *.npy"))
        self.label_12.setText(_translate("MainWindow", "Run"))
        self.pushButton_16.setText(_translate("MainWindow", "Run all"))
        self.pushButton_8.setText(_translate("MainWindow", "Spike Reduction"))
        self.pushButton_7.setText(_translate("MainWindow", "Run Segmentation"))
        self.pushButton_9.setText(_translate("MainWindow", "Run Binarization"))
        self.pushButton_10.setText(_translate("MainWindow", "Signal Extration"))
        self.label_15.setText(_translate("MainWindow", "Save"))
        self.label_18.setText(_translate("MainWindow", "1/6500"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "Data Process"))

