# coding: utf-8
# file generated by setuptools_scm + setup.py
# don't change, don't track in version control
git_hash = b'\xaa\xbd\x13\x89'
full_git_hash = 'aabd1389ca2034ed3700c523704875cdbf136705'
git_branch = 'HEAD'
dirty = False
