# Generated by Django 4.2.6 on 2023-10-12 13:28

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Document",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("slug", models.SlugField(unique=True)),
                (
                    "content",
                    models.TextField(
                        help_text="Markdown. First line could be {% extends 'xxxxxxx.html' %}"
                    ),
                ),
            ],
        ),
    ]
