# Generated by Django 4.2.4 on 2023-08-29 17:39

from django.db import migrations, models
import shortuuid.django_fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PrivateFile',
            fields=[
                ('id', shortuuid.django_fields.ShortUUIDField(alphabet=None, length=22, max_length=22, prefix='', primary_key=True, serialize=False)),
                ('file', models.FileField(blank=True, default=None, null=True, upload_to='private_files')),
                ('name', models.TextField(blank=True, default=None, null=True, unique=True)),
                ('filetype', models.TextField(blank=True, default=None, null=True)),
                ('notes', models.TextField(blank=True, default=None, null=True)),
                ('metadata', models.JSONField(blank=True, default=None, null=True)),
            ],
        ),
    ]
