


python -mpdb src/fredquery/plotobs.py --tslist BUSINV,MNFCTRIMNSA,MNFCTRIMSA,MNFCTRSMNSA,MNFCTRSMSA,RETAILIMNSA,RETAILIMSA,RETAILSMNSA,RETAILSMSA,TOTBUSIMNSA,TOTBUSSMNSA,TOTBUSSMSA,WHLSLRIMNSA,WHLSLRIMSA,WHLSLRSMNSA,WHLSLRSMSA

