
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2024-03-15T12:09:15-0400",
 "dirty": false,
 "error": null,
 "full-revisionid": "fdec7b5ef4ad9eb200b793004c6190ff8e3cf851",
 "version": "2.32.0rc2"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
