from antlr4 import *
from vba_likeParser import vba_likeParser as vba_likeParser

class vba_likeVisitor(ParseTreeVisitor):
    def visitProgram(self, ctx: vba_likeParser.ProgramContext): ...
    def visitLikePatternElement(self, ctx: vba_likeParser.LikePatternElementContext): ...
    def visitLikePatternChar(self, ctx: vba_likeParser.LikePatternCharContext): ...
    def visitWildcard(self, ctx: vba_likeParser.WildcardContext): ...
    def visitLikePatternCharlist(self, ctx: vba_likeParser.LikePatternCharlistContext): ...
    def visitCharList(self, ctx: vba_likeParser.CharListContext): ...
    def visitCharListElement(self, ctx: vba_likeParser.CharListElementContext): ...
    def visitCharlistChar(self, ctx: vba_likeParser.CharlistCharContext): ...
    def visitCharRange(self, ctx: vba_likeParser.CharRangeContext): ...
