# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: BinaryOp.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='BinaryOp.proto',
  package='mojo.spec',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x0e\x42inaryOp.proto\x12\tmojo.spec\"\xd9\x01\n\rConstBinaryOp\x12%\n\x04type\x18\x01 \x01(\x0e\x32\x17.mojo.spec.BinaryOpType\x12(\n\x03pos\x18\x02 \x01(\x0e\x32\x1b.mojo.spec.BinaryOpPosition\x12\x13\n\tint32_val\x18\x03 \x01(\x05H\x00\x12\x13\n\tint64_val\x18\x04 \x01(\x03H\x00\x12\x15\n\x0b\x66loat32_val\x18\x05 \x01(\x02H\x00\x12\x15\n\x0b\x66loat64_val\x18\x06 \x01(\x01H\x00\x12\x12\n\x08\x62ool_val\x18\x07 \x01(\x08H\x00\x42\x0b\n\tconst_val\"j\n\x08\x42inaryOp\x12%\n\x04type\x18\x01 \x01(\x0e\x32\x17.mojo.spec.BinaryOpType\x12\x15\n\x0b\x66loat32_eps\x18\x02 \x01(\x02H\x00\x12\x15\n\x0b\x66loat64_eps\x18\x03 \x01(\x01H\x00\x42\t\n\x07\x65psilon*p\n\x0c\x42inaryOpType\x12\x1a\n\x16UNKNOWN_BINARY_OP_TYPE\x10\x00\x12\x07\n\x03\x41\x44\x44\x10\x01\x12\x0c\n\x08SUBTRACT\x10\x02\x12\x0c\n\x08MULTIPLY\x10\x03\x12\n\n\x06\x44IVIDE\x10\x04\x12\x07\n\x03POW\x10\x05\x12\n\n\x06MODULO\x10\x06*G\n\x10\x42inaryOpPosition\x12\x1e\n\x1aUNKNOWN_BINARY_OP_POSITION\x10\x00\x12\x08\n\x04LEFT\x10\x01\x12\t\n\x05RIGHT\x10\x02\x62\x06proto3')
)

_BINARYOPTYPE = _descriptor.EnumDescriptor(
  name='BinaryOpType',
  full_name='mojo.spec.BinaryOpType',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='UNKNOWN_BINARY_OP_TYPE', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='ADD', index=1, number=1,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='SUBTRACT', index=2, number=2,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='MULTIPLY', index=3, number=3,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='DIVIDE', index=4, number=4,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='POW', index=5, number=5,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='MODULO', index=6, number=6,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=357,
  serialized_end=469,
)
_sym_db.RegisterEnumDescriptor(_BINARYOPTYPE)

BinaryOpType = enum_type_wrapper.EnumTypeWrapper(_BINARYOPTYPE)
_BINARYOPPOSITION = _descriptor.EnumDescriptor(
  name='BinaryOpPosition',
  full_name='mojo.spec.BinaryOpPosition',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='UNKNOWN_BINARY_OP_POSITION', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='LEFT', index=1, number=1,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='RIGHT', index=2, number=2,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=471,
  serialized_end=542,
)
_sym_db.RegisterEnumDescriptor(_BINARYOPPOSITION)

BinaryOpPosition = enum_type_wrapper.EnumTypeWrapper(_BINARYOPPOSITION)
UNKNOWN_BINARY_OP_TYPE = 0
ADD = 1
SUBTRACT = 2
MULTIPLY = 3
DIVIDE = 4
POW = 5
MODULO = 6
UNKNOWN_BINARY_OP_POSITION = 0
LEFT = 1
RIGHT = 2



_CONSTBINARYOP = _descriptor.Descriptor(
  name='ConstBinaryOp',
  full_name='mojo.spec.ConstBinaryOp',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='type', full_name='mojo.spec.ConstBinaryOp.type', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='pos', full_name='mojo.spec.ConstBinaryOp.pos', index=1,
      number=2, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='int32_val', full_name='mojo.spec.ConstBinaryOp.int32_val', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='int64_val', full_name='mojo.spec.ConstBinaryOp.int64_val', index=3,
      number=4, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='float32_val', full_name='mojo.spec.ConstBinaryOp.float32_val', index=4,
      number=5, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='float64_val', full_name='mojo.spec.ConstBinaryOp.float64_val', index=5,
      number=6, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='bool_val', full_name='mojo.spec.ConstBinaryOp.bool_val', index=6,
      number=7, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='const_val', full_name='mojo.spec.ConstBinaryOp.const_val',
      index=0, containing_type=None, fields=[]),
  ],
  serialized_start=30,
  serialized_end=247,
)


_BINARYOP = _descriptor.Descriptor(
  name='BinaryOp',
  full_name='mojo.spec.BinaryOp',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='type', full_name='mojo.spec.BinaryOp.type', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='float32_eps', full_name='mojo.spec.BinaryOp.float32_eps', index=1,
      number=2, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='float64_eps', full_name='mojo.spec.BinaryOp.float64_eps', index=2,
      number=3, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='epsilon', full_name='mojo.spec.BinaryOp.epsilon',
      index=0, containing_type=None, fields=[]),
  ],
  serialized_start=249,
  serialized_end=355,
)

_CONSTBINARYOP.fields_by_name['type'].enum_type = _BINARYOPTYPE
_CONSTBINARYOP.fields_by_name['pos'].enum_type = _BINARYOPPOSITION
_CONSTBINARYOP.oneofs_by_name['const_val'].fields.append(
  _CONSTBINARYOP.fields_by_name['int32_val'])
_CONSTBINARYOP.fields_by_name['int32_val'].containing_oneof = _CONSTBINARYOP.oneofs_by_name['const_val']
_CONSTBINARYOP.oneofs_by_name['const_val'].fields.append(
  _CONSTBINARYOP.fields_by_name['int64_val'])
_CONSTBINARYOP.fields_by_name['int64_val'].containing_oneof = _CONSTBINARYOP.oneofs_by_name['const_val']
_CONSTBINARYOP.oneofs_by_name['const_val'].fields.append(
  _CONSTBINARYOP.fields_by_name['float32_val'])
_CONSTBINARYOP.fields_by_name['float32_val'].containing_oneof = _CONSTBINARYOP.oneofs_by_name['const_val']
_CONSTBINARYOP.oneofs_by_name['const_val'].fields.append(
  _CONSTBINARYOP.fields_by_name['float64_val'])
_CONSTBINARYOP.fields_by_name['float64_val'].containing_oneof = _CONSTBINARYOP.oneofs_by_name['const_val']
_CONSTBINARYOP.oneofs_by_name['const_val'].fields.append(
  _CONSTBINARYOP.fields_by_name['bool_val'])
_CONSTBINARYOP.fields_by_name['bool_val'].containing_oneof = _CONSTBINARYOP.oneofs_by_name['const_val']
_BINARYOP.fields_by_name['type'].enum_type = _BINARYOPTYPE
_BINARYOP.oneofs_by_name['epsilon'].fields.append(
  _BINARYOP.fields_by_name['float32_eps'])
_BINARYOP.fields_by_name['float32_eps'].containing_oneof = _BINARYOP.oneofs_by_name['epsilon']
_BINARYOP.oneofs_by_name['epsilon'].fields.append(
  _BINARYOP.fields_by_name['float64_eps'])
_BINARYOP.fields_by_name['float64_eps'].containing_oneof = _BINARYOP.oneofs_by_name['epsilon']
DESCRIPTOR.message_types_by_name['ConstBinaryOp'] = _CONSTBINARYOP
DESCRIPTOR.message_types_by_name['BinaryOp'] = _BINARYOP
DESCRIPTOR.enum_types_by_name['BinaryOpType'] = _BINARYOPTYPE
DESCRIPTOR.enum_types_by_name['BinaryOpPosition'] = _BINARYOPPOSITION
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ConstBinaryOp = _reflection.GeneratedProtocolMessageType('ConstBinaryOp', (_message.Message,), {
  'DESCRIPTOR' : _CONSTBINARYOP,
  '__module__' : 'BinaryOp_pb2'
  # @@protoc_insertion_point(class_scope:mojo.spec.ConstBinaryOp)
  })
_sym_db.RegisterMessage(ConstBinaryOp)

BinaryOp = _reflection.GeneratedProtocolMessageType('BinaryOp', (_message.Message,), {
  'DESCRIPTOR' : _BINARYOP,
  '__module__' : 'BinaryOp_pb2'
  # @@protoc_insertion_point(class_scope:mojo.spec.BinaryOp)
  })
_sym_db.RegisterMessage(BinaryOp)


# @@protoc_insertion_point(module_scope)
