# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Math.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import daimojo.Map_pb2 as Map__pb2
try:
  Column__pb2 = Map__pb2.Column__pb2
except AttributeError:
  Column__pb2 = Map__pb2.Column_pb2

from daimojo.Map_pb2 import *

DESCRIPTOR = _descriptor.FileDescriptor(
  name='Math.proto',
  package='mojo.spec',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\nMath.proto\x12\tmojo.spec\x1a\tMap.proto\"\x07\n\x05\x45xpOp\"\t\n\x07\x45xpM1Op\"\x0b\n\tSigmoidOp\"\x16\n\x07PowerOp\x12\x0b\n\x03\x65xp\x18\x01 \x01(\x01\"\x07\n\x05LogOp\"\x08\n\x06SqrtOp\"\x0b\n\tSoftmaxOp\"\n\n\x08MedianOp\"\x19\n\x08MomentOp\x12\r\n\x05order\x18\x01 \x01(\x05\"0\n\x0bNormalizeOp\x12!\n\x04type\x18\x01 \x01(\x0e\x32\x13.mojo.spec.NormType\"\xce\x01\n\x06\x43lipOp\x12\x13\n\tint32_min\x18\x01 \x01(\x05H\x00\x12\x13\n\tint64_min\x18\x02 \x01(\x03H\x00\x12\x15\n\x0b\x66loat32_min\x18\x03 \x01(\x02H\x00\x12\x15\n\x0b\x66loat64_min\x18\x04 \x01(\x01H\x00\x12\x13\n\tint32_max\x18\x05 \x01(\x05H\x01\x12\x13\n\tint64_max\x18\x06 \x01(\x03H\x01\x12\x15\n\x0b\x66loat32_max\x18\x07 \x01(\x02H\x01\x12\x15\n\x0b\x66loat64_max\x18\x08 \x01(\x01H\x01\x42\t\n\x07min_valB\t\n\x07max_val\"f\n\x08KMeansOp\x12#\n\x04type\x18\x01 \x01(\x0e\x32\x15.mojo.spec.KMeansType\x12\t\n\x01k\x18\x02 \x01(\x05\x12*\n\tcentroids\x18\x03 \x01(\x0b\x32\x17.mojo.spec.ExternalData\"?\n\x0fMatrixProductOp\x12,\n\x0bmatrix_data\x18\x01 \x01(\x0b\x32\x17.mojo.spec.ExternalData\"&\n\x07ScaleOp\x12\x0c\n\x04mean\x18\x01 \x01(\x01\x12\r\n\x05scale\x18\x02 \x01(\x01*D\n\x08NormType\x12\x10\n\x0cUNKNOWN_NORM\x10\x00\x12\x0b\n\x07L1_NORM\x10\x01\x12\x0b\n\x07L2_NORM\x10\x02\x12\x0c\n\x08MAX_NORM\x10\x03*>\n\nKMeansType\x12\x17\n\x13UNKNOWN_KMEANS_TYPE\x10\x00\x12\x0c\n\x08\x44ISTANCE\x10\x01\x12\t\n\x05LABEL\x10\x02P\x00\x62\x06proto3')
  ,
  dependencies=[Map__pb2.DESCRIPTOR,],
  public_dependencies=[Map__pb2.DESCRIPTOR,])

_NORMTYPE = _descriptor.EnumDescriptor(
  name='NormType',
  full_name='mojo.spec.NormType',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='UNKNOWN_NORM', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='L1_NORM', index=1, number=1,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='L2_NORM', index=2, number=2,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='MAX_NORM', index=3, number=3,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=632,
  serialized_end=700,
)
_sym_db.RegisterEnumDescriptor(_NORMTYPE)

NormType = enum_type_wrapper.EnumTypeWrapper(_NORMTYPE)
_KMEANSTYPE = _descriptor.EnumDescriptor(
  name='KMeansType',
  full_name='mojo.spec.KMeansType',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='UNKNOWN_KMEANS_TYPE', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='DISTANCE', index=1, number=1,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='LABEL', index=2, number=2,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=702,
  serialized_end=764,
)
_sym_db.RegisterEnumDescriptor(_KMEANSTYPE)

KMeansType = enum_type_wrapper.EnumTypeWrapper(_KMEANSTYPE)
UNKNOWN_NORM = 0
L1_NORM = 1
L2_NORM = 2
MAX_NORM = 3
UNKNOWN_KMEANS_TYPE = 0
DISTANCE = 1
LABEL = 2



_EXPOP = _descriptor.Descriptor(
  name='ExpOp',
  full_name='mojo.spec.ExpOp',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=36,
  serialized_end=43,
)


_EXPM1OP = _descriptor.Descriptor(
  name='ExpM1Op',
  full_name='mojo.spec.ExpM1Op',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=45,
  serialized_end=54,
)


_SIGMOIDOP = _descriptor.Descriptor(
  name='SigmoidOp',
  full_name='mojo.spec.SigmoidOp',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=56,
  serialized_end=67,
)


_POWEROP = _descriptor.Descriptor(
  name='PowerOp',
  full_name='mojo.spec.PowerOp',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='exp', full_name='mojo.spec.PowerOp.exp', index=0,
      number=1, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=69,
  serialized_end=91,
)


_LOGOP = _descriptor.Descriptor(
  name='LogOp',
  full_name='mojo.spec.LogOp',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=93,
  serialized_end=100,
)


_SQRTOP = _descriptor.Descriptor(
  name='SqrtOp',
  full_name='mojo.spec.SqrtOp',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=102,
  serialized_end=110,
)


_SOFTMAXOP = _descriptor.Descriptor(
  name='SoftmaxOp',
  full_name='mojo.spec.SoftmaxOp',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=112,
  serialized_end=123,
)


_MEDIANOP = _descriptor.Descriptor(
  name='MedianOp',
  full_name='mojo.spec.MedianOp',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=125,
  serialized_end=135,
)


_MOMENTOP = _descriptor.Descriptor(
  name='MomentOp',
  full_name='mojo.spec.MomentOp',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='order', full_name='mojo.spec.MomentOp.order', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=137,
  serialized_end=162,
)


_NORMALIZEOP = _descriptor.Descriptor(
  name='NormalizeOp',
  full_name='mojo.spec.NormalizeOp',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='type', full_name='mojo.spec.NormalizeOp.type', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=164,
  serialized_end=212,
)


_CLIPOP = _descriptor.Descriptor(
  name='ClipOp',
  full_name='mojo.spec.ClipOp',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='int32_min', full_name='mojo.spec.ClipOp.int32_min', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='int64_min', full_name='mojo.spec.ClipOp.int64_min', index=1,
      number=2, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='float32_min', full_name='mojo.spec.ClipOp.float32_min', index=2,
      number=3, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='float64_min', full_name='mojo.spec.ClipOp.float64_min', index=3,
      number=4, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='int32_max', full_name='mojo.spec.ClipOp.int32_max', index=4,
      number=5, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='int64_max', full_name='mojo.spec.ClipOp.int64_max', index=5,
      number=6, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='float32_max', full_name='mojo.spec.ClipOp.float32_max', index=6,
      number=7, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='float64_max', full_name='mojo.spec.ClipOp.float64_max', index=7,
      number=8, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='min_val', full_name='mojo.spec.ClipOp.min_val',
      index=0, containing_type=None, fields=[]),
    _descriptor.OneofDescriptor(
      name='max_val', full_name='mojo.spec.ClipOp.max_val',
      index=1, containing_type=None, fields=[]),
  ],
  serialized_start=215,
  serialized_end=421,
)


_KMEANSOP = _descriptor.Descriptor(
  name='KMeansOp',
  full_name='mojo.spec.KMeansOp',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='type', full_name='mojo.spec.KMeansOp.type', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='k', full_name='mojo.spec.KMeansOp.k', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='centroids', full_name='mojo.spec.KMeansOp.centroids', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=423,
  serialized_end=525,
)


_MATRIXPRODUCTOP = _descriptor.Descriptor(
  name='MatrixProductOp',
  full_name='mojo.spec.MatrixProductOp',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='matrix_data', full_name='mojo.spec.MatrixProductOp.matrix_data', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=527,
  serialized_end=590,
)


_SCALEOP = _descriptor.Descriptor(
  name='ScaleOp',
  full_name='mojo.spec.ScaleOp',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='mean', full_name='mojo.spec.ScaleOp.mean', index=0,
      number=1, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='scale', full_name='mojo.spec.ScaleOp.scale', index=1,
      number=2, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=592,
  serialized_end=630,
)

_NORMALIZEOP.fields_by_name['type'].enum_type = _NORMTYPE
_CLIPOP.oneofs_by_name['min_val'].fields.append(
  _CLIPOP.fields_by_name['int32_min'])
_CLIPOP.fields_by_name['int32_min'].containing_oneof = _CLIPOP.oneofs_by_name['min_val']
_CLIPOP.oneofs_by_name['min_val'].fields.append(
  _CLIPOP.fields_by_name['int64_min'])
_CLIPOP.fields_by_name['int64_min'].containing_oneof = _CLIPOP.oneofs_by_name['min_val']
_CLIPOP.oneofs_by_name['min_val'].fields.append(
  _CLIPOP.fields_by_name['float32_min'])
_CLIPOP.fields_by_name['float32_min'].containing_oneof = _CLIPOP.oneofs_by_name['min_val']
_CLIPOP.oneofs_by_name['min_val'].fields.append(
  _CLIPOP.fields_by_name['float64_min'])
_CLIPOP.fields_by_name['float64_min'].containing_oneof = _CLIPOP.oneofs_by_name['min_val']
_CLIPOP.oneofs_by_name['max_val'].fields.append(
  _CLIPOP.fields_by_name['int32_max'])
_CLIPOP.fields_by_name['int32_max'].containing_oneof = _CLIPOP.oneofs_by_name['max_val']
_CLIPOP.oneofs_by_name['max_val'].fields.append(
  _CLIPOP.fields_by_name['int64_max'])
_CLIPOP.fields_by_name['int64_max'].containing_oneof = _CLIPOP.oneofs_by_name['max_val']
_CLIPOP.oneofs_by_name['max_val'].fields.append(
  _CLIPOP.fields_by_name['float32_max'])
_CLIPOP.fields_by_name['float32_max'].containing_oneof = _CLIPOP.oneofs_by_name['max_val']
_CLIPOP.oneofs_by_name['max_val'].fields.append(
  _CLIPOP.fields_by_name['float64_max'])
_CLIPOP.fields_by_name['float64_max'].containing_oneof = _CLIPOP.oneofs_by_name['max_val']
_KMEANSOP.fields_by_name['type'].enum_type = _KMEANSTYPE
_KMEANSOP.fields_by_name['centroids'].message_type = Map__pb2._EXTERNALDATA
_MATRIXPRODUCTOP.fields_by_name['matrix_data'].message_type = Map__pb2._EXTERNALDATA
DESCRIPTOR.message_types_by_name['ExpOp'] = _EXPOP
DESCRIPTOR.message_types_by_name['ExpM1Op'] = _EXPM1OP
DESCRIPTOR.message_types_by_name['SigmoidOp'] = _SIGMOIDOP
DESCRIPTOR.message_types_by_name['PowerOp'] = _POWEROP
DESCRIPTOR.message_types_by_name['LogOp'] = _LOGOP
DESCRIPTOR.message_types_by_name['SqrtOp'] = _SQRTOP
DESCRIPTOR.message_types_by_name['SoftmaxOp'] = _SOFTMAXOP
DESCRIPTOR.message_types_by_name['MedianOp'] = _MEDIANOP
DESCRIPTOR.message_types_by_name['MomentOp'] = _MOMENTOP
DESCRIPTOR.message_types_by_name['NormalizeOp'] = _NORMALIZEOP
DESCRIPTOR.message_types_by_name['ClipOp'] = _CLIPOP
DESCRIPTOR.message_types_by_name['KMeansOp'] = _KMEANSOP
DESCRIPTOR.message_types_by_name['MatrixProductOp'] = _MATRIXPRODUCTOP
DESCRIPTOR.message_types_by_name['ScaleOp'] = _SCALEOP
DESCRIPTOR.enum_types_by_name['NormType'] = _NORMTYPE
DESCRIPTOR.enum_types_by_name['KMeansType'] = _KMEANSTYPE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ExpOp = _reflection.GeneratedProtocolMessageType('ExpOp', (_message.Message,), {
  'DESCRIPTOR' : _EXPOP,
  '__module__' : 'Math_pb2'
  # @@protoc_insertion_point(class_scope:mojo.spec.ExpOp)
  })
_sym_db.RegisterMessage(ExpOp)

ExpM1Op = _reflection.GeneratedProtocolMessageType('ExpM1Op', (_message.Message,), {
  'DESCRIPTOR' : _EXPM1OP,
  '__module__' : 'Math_pb2'
  # @@protoc_insertion_point(class_scope:mojo.spec.ExpM1Op)
  })
_sym_db.RegisterMessage(ExpM1Op)

SigmoidOp = _reflection.GeneratedProtocolMessageType('SigmoidOp', (_message.Message,), {
  'DESCRIPTOR' : _SIGMOIDOP,
  '__module__' : 'Math_pb2'
  # @@protoc_insertion_point(class_scope:mojo.spec.SigmoidOp)
  })
_sym_db.RegisterMessage(SigmoidOp)

PowerOp = _reflection.GeneratedProtocolMessageType('PowerOp', (_message.Message,), {
  'DESCRIPTOR' : _POWEROP,
  '__module__' : 'Math_pb2'
  # @@protoc_insertion_point(class_scope:mojo.spec.PowerOp)
  })
_sym_db.RegisterMessage(PowerOp)

LogOp = _reflection.GeneratedProtocolMessageType('LogOp', (_message.Message,), {
  'DESCRIPTOR' : _LOGOP,
  '__module__' : 'Math_pb2'
  # @@protoc_insertion_point(class_scope:mojo.spec.LogOp)
  })
_sym_db.RegisterMessage(LogOp)

SqrtOp = _reflection.GeneratedProtocolMessageType('SqrtOp', (_message.Message,), {
  'DESCRIPTOR' : _SQRTOP,
  '__module__' : 'Math_pb2'
  # @@protoc_insertion_point(class_scope:mojo.spec.SqrtOp)
  })
_sym_db.RegisterMessage(SqrtOp)

SoftmaxOp = _reflection.GeneratedProtocolMessageType('SoftmaxOp', (_message.Message,), {
  'DESCRIPTOR' : _SOFTMAXOP,
  '__module__' : 'Math_pb2'
  # @@protoc_insertion_point(class_scope:mojo.spec.SoftmaxOp)
  })
_sym_db.RegisterMessage(SoftmaxOp)

MedianOp = _reflection.GeneratedProtocolMessageType('MedianOp', (_message.Message,), {
  'DESCRIPTOR' : _MEDIANOP,
  '__module__' : 'Math_pb2'
  # @@protoc_insertion_point(class_scope:mojo.spec.MedianOp)
  })
_sym_db.RegisterMessage(MedianOp)

MomentOp = _reflection.GeneratedProtocolMessageType('MomentOp', (_message.Message,), {
  'DESCRIPTOR' : _MOMENTOP,
  '__module__' : 'Math_pb2'
  # @@protoc_insertion_point(class_scope:mojo.spec.MomentOp)
  })
_sym_db.RegisterMessage(MomentOp)

NormalizeOp = _reflection.GeneratedProtocolMessageType('NormalizeOp', (_message.Message,), {
  'DESCRIPTOR' : _NORMALIZEOP,
  '__module__' : 'Math_pb2'
  # @@protoc_insertion_point(class_scope:mojo.spec.NormalizeOp)
  })
_sym_db.RegisterMessage(NormalizeOp)

ClipOp = _reflection.GeneratedProtocolMessageType('ClipOp', (_message.Message,), {
  'DESCRIPTOR' : _CLIPOP,
  '__module__' : 'Math_pb2'
  # @@protoc_insertion_point(class_scope:mojo.spec.ClipOp)
  })
_sym_db.RegisterMessage(ClipOp)

KMeansOp = _reflection.GeneratedProtocolMessageType('KMeansOp', (_message.Message,), {
  'DESCRIPTOR' : _KMEANSOP,
  '__module__' : 'Math_pb2'
  # @@protoc_insertion_point(class_scope:mojo.spec.KMeansOp)
  })
_sym_db.RegisterMessage(KMeansOp)

MatrixProductOp = _reflection.GeneratedProtocolMessageType('MatrixProductOp', (_message.Message,), {
  'DESCRIPTOR' : _MATRIXPRODUCTOP,
  '__module__' : 'Math_pb2'
  # @@protoc_insertion_point(class_scope:mojo.spec.MatrixProductOp)
  })
_sym_db.RegisterMessage(MatrixProductOp)

ScaleOp = _reflection.GeneratedProtocolMessageType('ScaleOp', (_message.Message,), {
  'DESCRIPTOR' : _SCALEOP,
  '__module__' : 'Math_pb2'
  # @@protoc_insertion_point(class_scope:mojo.spec.ScaleOp)
  })
_sym_db.RegisterMessage(ScaleOp)


# @@protoc_insertion_point(module_scope)
