# Generated by Django 4.1.1 on 2023-09-25 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0008_menu_exclude_menu'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='is_initial_data',
            field=models.BooleanField(default=False),
        ),
    ]
