# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Ftrl.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import daimojo.Map_pb2 as Map__pb2
try:
  Column__pb2 = Map__pb2.Column__pb2
except AttributeError:
  Column__pb2 = Map__pb2.Column_pb2

from daimojo.Map_pb2 import *

DESCRIPTOR = _descriptor.FileDescriptor(
  name='Ftrl.proto',
  package='mojo.spec',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\nFtrl.proto\x12\tmojo.spec\x1a\tMap.proto\"\x90\x03\n\x06\x46trlOp\x12\x0f\n\x07nlabels\x18\x01 \x01(\x05\x12\x11\n\tnfeatures\x18\x02 \x01(\x05\x12\x15\n\rninteractions\x18\x03 \x01(\x05\x12\r\n\x05\x61lpha\x18\x04 \x01(\x01\x12\x0c\n\x04\x62\x65ta\x18\x05 \x01(\x01\x12\x0f\n\x07lambda1\x18\x06 \x01(\x01\x12\x0f\n\x07lambda2\x18\x07 \x01(\x01\x12,\n\nmodel_type\x18\x08 \x01(\x0e\x32\x18.mojo.spec.FtrlModelType\x12\x16\n\x0emantissa_nbits\x18\t \x01(\x05\x12\r\n\x05nbins\x18\n \x01(\x05\x12\"\n\x01z\x18\x0b \x01(\x0b\x32\x17.mojo.spec.ExternalData\x12\"\n\x01n\x18\x0c \x01(\x0b\x32\x17.mojo.spec.ExternalData\x12+\n\x0cinteractions\x18\r \x03(\x0b\x32\x15.mojo.spec.Int32Array\x12\x16\n\x0e\x64\x61ta_label_ids\x18\x0e \x03(\x05\x12\x13\n\x0bmodel_nrows\x18\x0f \x01(\x05\x12\x15\n\rfeature_names\x18\x10 \x03(\t*[\n\rFtrlModelType\x12\x1b\n\x17UNKNOWN_FTRL_MODEL_TYPE\x10\x00\x12\x0e\n\nREGRESSION\x10\x01\x12\x0c\n\x08\x42INOMIAL\x10\x02\x12\x0f\n\x0bMULTINOMIAL\x10\x03P\x00\x62\x06proto3')
  ,
  dependencies=[Map__pb2.DESCRIPTOR,],
  public_dependencies=[Map__pb2.DESCRIPTOR,])

_FTRLMODELTYPE = _descriptor.EnumDescriptor(
  name='FtrlModelType',
  full_name='mojo.spec.FtrlModelType',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='UNKNOWN_FTRL_MODEL_TYPE', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='REGRESSION', index=1, number=1,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='BINOMIAL', index=2, number=2,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='MULTINOMIAL', index=3, number=3,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=439,
  serialized_end=530,
)
_sym_db.RegisterEnumDescriptor(_FTRLMODELTYPE)

FtrlModelType = enum_type_wrapper.EnumTypeWrapper(_FTRLMODELTYPE)
UNKNOWN_FTRL_MODEL_TYPE = 0
REGRESSION = 1
BINOMIAL = 2
MULTINOMIAL = 3



_FTRLOP = _descriptor.Descriptor(
  name='FtrlOp',
  full_name='mojo.spec.FtrlOp',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='nlabels', full_name='mojo.spec.FtrlOp.nlabels', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='nfeatures', full_name='mojo.spec.FtrlOp.nfeatures', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='ninteractions', full_name='mojo.spec.FtrlOp.ninteractions', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='alpha', full_name='mojo.spec.FtrlOp.alpha', index=3,
      number=4, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='beta', full_name='mojo.spec.FtrlOp.beta', index=4,
      number=5, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='lambda1', full_name='mojo.spec.FtrlOp.lambda1', index=5,
      number=6, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='lambda2', full_name='mojo.spec.FtrlOp.lambda2', index=6,
      number=7, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='model_type', full_name='mojo.spec.FtrlOp.model_type', index=7,
      number=8, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='mantissa_nbits', full_name='mojo.spec.FtrlOp.mantissa_nbits', index=8,
      number=9, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='nbins', full_name='mojo.spec.FtrlOp.nbins', index=9,
      number=10, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='z', full_name='mojo.spec.FtrlOp.z', index=10,
      number=11, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='n', full_name='mojo.spec.FtrlOp.n', index=11,
      number=12, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='interactions', full_name='mojo.spec.FtrlOp.interactions', index=12,
      number=13, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='data_label_ids', full_name='mojo.spec.FtrlOp.data_label_ids', index=13,
      number=14, type=5, cpp_type=1, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='model_nrows', full_name='mojo.spec.FtrlOp.model_nrows', index=14,
      number=15, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='feature_names', full_name='mojo.spec.FtrlOp.feature_names', index=15,
      number=16, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=37,
  serialized_end=437,
)

_FTRLOP.fields_by_name['model_type'].enum_type = _FTRLMODELTYPE
_FTRLOP.fields_by_name['z'].message_type = Map__pb2._EXTERNALDATA
_FTRLOP.fields_by_name['n'].message_type = Map__pb2._EXTERNALDATA
_FTRLOP.fields_by_name['interactions'].message_type = Map__pb2._INT32ARRAY
DESCRIPTOR.message_types_by_name['FtrlOp'] = _FTRLOP
DESCRIPTOR.enum_types_by_name['FtrlModelType'] = _FTRLMODELTYPE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

FtrlOp = _reflection.GeneratedProtocolMessageType('FtrlOp', (_message.Message,), {
  'DESCRIPTOR' : _FTRLOP,
  '__module__' : 'Ftrl_pb2'
  # @@protoc_insertion_point(class_scope:mojo.spec.FtrlOp)
  })
_sym_db.RegisterMessage(FtrlOp)


# @@protoc_insertion_point(module_scope)
