
# This file was generated by 'versioneer.py' (0.21) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2024-03-15T08:14:57-0500",
 "dirty": false,
 "error": null,
 "full-revisionid": "5fc8a3a2864dbbfc15faab3acf6afaa524adf584",
 "version": "0.4.13"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
