
# This file was generated by 'versioneer.py' (0.29) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2024-03-14T06:18:13+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "4c73818a6da7a14b39beafab648e3d1d4c848c86",
 "version": "0.0.17"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
