
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2024-03-17T17:16:57-0400",
 "dirty": false,
 "error": null,
 "full-revisionid": "6198055dfe35f205bf0cfd66d71b317e74ef52d3",
 "version": "2024.3.17"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
