
# This file was generated by 'versioneer.py' (0.28) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2024-03-13T15:59:42+0100",
 "dirty": true,
 "error": null,
 "full-revisionid": "4957bb60f51c39ecf85747f80f84f97ddd85f261",
 "version": "0.1.2"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
