
# This file was generated by 'versioneer.py' (0.29) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2024-03-15T14:39:35+0800",
 "dirty": false,
 "error": null,
 "full-revisionid": "af656af762056d468b8ef1678ae04d21f6d2b3c3",
 "version": "0.9.3"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
