# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/00_cons.ipynb.

# %% auto 0
__all__ = ['WRAPS_ASSIGN_ANNDOCS']

# %% ../nbs/00_cons.ipynb 6
#| export


# %% ../nbs/00_cons.ipynb 8
#| export



# %% ../nbs/00_cons.ipynb 10
#| export


# %% ../nbs/00_cons.ipynb 12
from nlit import (
    COORD, SLICE,
    __DOC__, __MODULE__, __ANNOTATIONS__
)

# %% ../nbs/00_cons.ipynb 14
#| export


# %% ../nbs/00_cons.ipynb 17
WRAPS_ASSIGN_ANNDOCS = (__DOC__, __MODULE__, __ANNOTATIONS__)

# %% ../nbs/00_cons.ipynb 19
#| export


# %% ../nbs/00_cons.ipynb 21
#| export


# %% ../nbs/00_cons.ipynb 23
#| export
