# Generated by Django 4.0.2 on 2024-01-01 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('remotejwt_user', '0003_alter_user_email_user_user_email_type_unique'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='first name'),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='last name'),
        ),
    ]
