
# This file was generated by 'versioneer.py' (0.21) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2024-03-15T17:21:24+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "345f6aa38a812021151ed08fa2c42e81846ef358",
 "version": "0.7.8"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
