
# This file was generated by 'versioneer.py' (0.28) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2024-03-18T12:16:11+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "4c4c24f7ab5d93eab2a03ae779782bfa9d4f2b6a",
 "version": "1.0.4"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
