# coding: utf-8

"""
    Livoltek API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class InlineResponse2008(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'data': 'InlineResponse2008Data',
        'message': 'object',
        'msg_code': 'object'
    }

    attribute_map = {
        'data': 'data',
        'message': 'message',
        'msg_code': 'msgCode'
    }

    def __init__(self, data=None, message=None, msg_code=None):  # noqa: E501
        """InlineResponse2008 - a model defined in Swagger"""  # noqa: E501
        self._data = None
        self._message = None
        self._msg_code = None
        self.discriminator = None
        if data is not None:
            self.data = data
        if message is not None:
            self.message = message
        if msg_code is not None:
            self.msg_code = msg_code

    @property
    def data(self):
        """Gets the data of this InlineResponse2008.  # noqa: E501


        :return: The data of this InlineResponse2008.  # noqa: E501
        :rtype: InlineResponse2008Data
        """
        return self._data

    @data.setter
    def data(self, data):
        """Sets the data of this InlineResponse2008.


        :param data: The data of this InlineResponse2008.  # noqa: E501
        :type: InlineResponse2008Data
        """

        self._data = data

    @property
    def message(self):
        """Gets the message of this InlineResponse2008.  # noqa: E501


        :return: The message of this InlineResponse2008.  # noqa: E501
        :rtype: object
        """
        return self._message

    @message.setter
    def message(self, message):
        """Sets the message of this InlineResponse2008.


        :param message: The message of this InlineResponse2008.  # noqa: E501
        :type: object
        """

        self._message = message

    @property
    def msg_code(self):
        """Gets the msg_code of this InlineResponse2008.  # noqa: E501


        :return: The msg_code of this InlineResponse2008.  # noqa: E501
        :rtype: object
        """
        return self._msg_code

    @msg_code.setter
    def msg_code(self, msg_code):
        """Sets the msg_code of this InlineResponse2008.


        :param msg_code: The msg_code of this InlineResponse2008.  # noqa: E501
        :type: object
        """

        self._msg_code = msg_code

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(InlineResponse2008, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, InlineResponse2008):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
