
# This file was generated by 'versioneer.py' (0.29) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2024-03-18T12:59:19+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "829e02f06bbf39937ec5bacc01bf82debf2d889f",
 "version": "1.6rc1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
