
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2024-03-13T13:32:47-0400",
 "dirty": false,
 "error": null,
 "full-revisionid": "a72a0986f771e3ed59e5e47dd2dc588ed6f68264",
 "version": "0.6.5"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
