# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Agg.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='Agg.proto',
  package='mojo.spec',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\tAgg.proto\x12\tmojo.spec\"+\n\x05\x41ggOp\x12\"\n\x04type\x18\x01 \x01(\x0e\x32\x14.mojo.spec.AggOpType*I\n\tAggOpType\x12\x17\n\x13UNKNOWN_AGG_OP_TYPE\x10\x00\x12\x07\n\x03SUM\x10\x01\x12\x08\n\x04PROD\x10\x02\x12\x07\n\x03MIN\x10\x03\x12\x07\n\x03MAX\x10\x04\x62\x06proto3')
)

_AGGOPTYPE = _descriptor.EnumDescriptor(
  name='AggOpType',
  full_name='mojo.spec.AggOpType',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='UNKNOWN_AGG_OP_TYPE', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='SUM', index=1, number=1,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='PROD', index=2, number=2,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='MIN', index=3, number=3,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='MAX', index=4, number=4,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=69,
  serialized_end=142,
)
_sym_db.RegisterEnumDescriptor(_AGGOPTYPE)

AggOpType = enum_type_wrapper.EnumTypeWrapper(_AGGOPTYPE)
UNKNOWN_AGG_OP_TYPE = 0
SUM = 1
PROD = 2
MIN = 3
MAX = 4



_AGGOP = _descriptor.Descriptor(
  name='AggOp',
  full_name='mojo.spec.AggOp',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='type', full_name='mojo.spec.AggOp.type', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=24,
  serialized_end=67,
)

_AGGOP.fields_by_name['type'].enum_type = _AGGOPTYPE
DESCRIPTOR.message_types_by_name['AggOp'] = _AGGOP
DESCRIPTOR.enum_types_by_name['AggOpType'] = _AGGOPTYPE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

AggOp = _reflection.GeneratedProtocolMessageType('AggOp', (_message.Message,), {
  'DESCRIPTOR' : _AGGOP,
  '__module__' : 'Agg_pb2'
  # @@protoc_insertion_point(class_scope:mojo.spec.AggOp)
  })
_sym_db.RegisterMessage(AggOp)


# @@protoc_insertion_point(module_scope)
