# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/01_atyp.ipynb.

# %% auto 0
__all__ = ['T', 'O', 'P', 'Ts', 'CoordFormat', 'SliceFormat', 'SliceFormats']

# %% ../nbs/01_atyp.ipynb 6
#| export


# %% ../nbs/01_atyp.ipynb 8
from typing import Union, Literal, TypeVar, ParamSpec, TypeAlias, TypeVarTuple

# %% ../nbs/01_atyp.ipynb 10
#| export


# %% ../nbs/01_atyp.ipynb 12
#| export


# %% ../nbs/01_atyp.ipynb 14
#| export


# %% ../nbs/01_atyp.ipynb 16
T = TypeVar('T')
'''Type variable for generic types''';

O = TypeVar('O')
'''Type variable for generic types reprenesting "other"''';

P = ParamSpec('P')
'''Parameter specification type variable, capturing the type of function parameters.''';

Ts = TypeVarTuple('Ts')

# %% ../nbs/01_atyp.ipynb 19
CoordFormat: TypeAlias = Literal['coord'];

SliceFormat: TypeAlias = Literal['slice'];

SliceFormats: TypeAlias = Union[CoordFormat, SliceFormat]

# %% ../nbs/01_atyp.ipynb 21
#| export
