
# This file was generated by 'versioneer.py' (0.28) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2024-03-13T09:01:46+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "4baaf7711af826c14406d56281436ce4f8c3cdd7",
 "version": "1.0.68"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
