
# This file was generated by 'versioneer.py' (0.28) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2024-03-14T18:12:02+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "be4432410e9e1e7c2467729d11157b588283cde3",
 "version": "1.0.2"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
