"""
    Cochl.Sense API

    Cochl.Sense API allows to detect what is contained inside sound data. Send audio data over the internet to discover what it contains.  ``` npx @openapitools/openapi-generator-cli generate -i openapi.json -g python -o python-client ```   # noqa: E501

    The version of the OpenAPI document: v1.6.0
    Contact: support@cochl.ai
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import cochl_sense_api
from cochl_sense_api.model.audio_metadatas import AudioMetadatas
from cochl_sense_api.model.audio_type import AudioType
from cochl_sense_api.model.default_sensitivity import DefaultSensitivity
from cochl_sense_api.model.tags_sensitivity import TagsSensitivity
from cochl_sense_api.model.window_hop import WindowHop
globals()['AudioMetadatas'] = AudioMetadatas
globals()['AudioType'] = AudioType
globals()['DefaultSensitivity'] = DefaultSensitivity
globals()['TagsSensitivity'] = TagsSensitivity
globals()['WindowHop'] = WindowHop
from cochl_sense_api.model.create_session import CreateSession


class TestCreateSession(unittest.TestCase):
    """CreateSession unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testCreateSession(self):
        """Test CreateSession"""
        # FIXME: construct object with mandatory attributes with example values
        # model = CreateSession()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
