"""
    Cochl.Sense API

    Cochl.Sense API allows to detect what is contained inside sound data. Send audio data over the internet to discover what it contains.  ``` npx @openapitools/openapi-generator-cli generate -i openapi.json -g python -o python-client ```   # noqa: E501

    The version of the OpenAPI document: v1.6.0
    Contact: support@cochl.ai
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import cochl_sense_api
from cochl_sense_api.model.page import Page
from cochl_sense_api.model.sense_event import SenseEvent
globals()['Page'] = Page
globals()['SenseEvent'] = SenseEvent
from cochl_sense_api.model.sense import Sense


class TestSense(unittest.TestCase):
    """Sense unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testSense(self):
        """Test Sense"""
        # FIXME: construct object with mandatory attributes with example values
        # model = Sense()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
