# Generated by sila2.code_generator; sila2.__version__: 0.11.4
from os.path import dirname, join

from sila2.framework import Feature

SiLAServiceFeature = Feature(join(dirname(__file__), "SiLAService.sila.xml"))
