

word_replacements = {
    "mts": "mt",
    "vsl": "vessel",
    "pct": "%",
    "dwat":"dwt",
    "s.dwat" : "summer dwt",
    "del" : "delivery",
    "dely" : "delivery",
    "delvy" : "delivery",
    "add" : "addcomm",
    "ad" : "addcomm",
    "comm":" ",
    "com" : " ",
    "disch" : "discharge",
    "disc":"discharge",
    "sgp":"singapore",
    "lycn" : "laycan",
    "l/c" : "laycan",
    "l / c" : "laycan",
    "lcan":"laycan",
    "acct" : "account",
    "pmax" : "panamax",
    "kmax":"kamsarmax",
    "kamax":"kamsarmax",
    "abt" : "about",
    "crgo":"cargo",
    "hk" : "hong kong",
    "ttl" : "total",
    "fwd" : "forward",
    "smx" : "supramax",
    "umx":"ultramax",
    'kmx':'kamsarmax',
    "blk" :"bulk",
    "jpn" : "japan",
    "adc":"addcomm",
    "dlosp" : "dropping last outward sea pilot",
    "lay" : "laycan",
    "addcomm" : "addcomm",
    "ordrs":"orders",
    "ordr":"order",
    'rm': 'residual marine',
    "spore": 'singapore',
    "alt"  : "alternative",
    "voy" : "voyage",
    "plsd" : "pleased",
    "rgds" : "regards",
    "brgds":"best regards",
    "dft":"draft",
    "pls" : "please",
    "wci" : "west coast of india",
    "pps" : "please provide suggestions",
    "cst" : "cost",
    "eca" : "emission control area",
    "qtty" : "quantity",
    "qty" : "quantity",
    "mos" : "month",
    "owrs" : "owners",
    "yrs" : 'years',
    "adcomm" : "addcomm",
    "hrs" : "hours",
    "gd" : "good",
    "gdday" : "good day",
    "pwwd" : "per weather working day",
    "tn" : "tonns",
    "blw" : "below",
    "req" : "required",
    "mtons" : "mt",
    "acc" : "account",
    "a/c" : "account",
    "goodday" : "good day",
    "sld" : "sailed",
    "'onw" : "onwards",
    "dur" : "duration",
    "\n":" -- ",
    "l/d":"load / discharge",
    "rdl" : "re delivery",
    "redlvy" : "re delivery",
    "delvy" : "delivery",
    "rge":"range",
    "redely" : "re delivery",
    "dischport":"discharge port"
    }
