from antlr4 import *
from vba_ccParser import vba_ccParser as vba_ccParser

class vba_ccVisitor(ParseTreeVisitor):
    def visitStartRule(self, ctx: vba_ccParser.StartRuleContext): ...
    def visitProceduralModuleHeader(self, ctx: vba_ccParser.ProceduralModuleHeaderContext): ...
    def visitClassFileHeader(self, ctx: vba_ccParser.ClassFileHeaderContext): ...
    def visitLogicalLine(self, ctx: vba_ccParser.LogicalLineContext): ...
    def visitConditionalModuleBody(self, ctx: vba_ccParser.ConditionalModuleBodyContext): ...
    def visitCcBlock(self, ctx: vba_ccParser.CcBlockContext): ...
    def visitCcConst(self, ctx: vba_ccParser.CcConstContext): ...
    def visitCcVarLhs(self, ctx: vba_ccParser.CcVarLhsContext): ...
    def visitCcIfBlock(self, ctx: vba_ccParser.CcIfBlockContext): ...
    def visitCcIf(self, ctx: vba_ccParser.CcIfContext): ...
    def visitCcElseifBlock(self, ctx: vba_ccParser.CcElseifBlockContext): ...
    def visitCcElseif(self, ctx: vba_ccParser.CcElseifContext): ...
    def visitCcElseBlock(self, ctx: vba_ccParser.CcElseBlockContext): ...
    def visitCcElse(self, ctx: vba_ccParser.CcElseContext): ...
    def visitCcEndif(self, ctx: vba_ccParser.CcEndifContext): ...
    def visitName(self, ctx: vba_ccParser.NameContext): ...
    def visitUntypedName(self, ctx: vba_ccParser.UntypedNameContext): ...
    def visitTypedName(self, ctx: vba_ccParser.TypedNameContext): ...
    def visitTypeSuffix(self, ctx: vba_ccParser.TypeSuffixContext): ...
    def visitParenthesizedExpression(self, ctx: vba_ccParser.ParenthesizedExpressionContext): ...
    def visitLiteralExpress(self, ctx: vba_ccParser.LiteralExpressContext): ...
    def visitUnaryMinusExpression(self, ctx: vba_ccParser.UnaryMinusExpressionContext): ...
    def visitRelationExpression(self, ctx: vba_ccParser.RelationExpressionContext): ...
    def visitIndexExpression(self, ctx: vba_ccParser.IndexExpressionContext): ...
    def visitNotOperatorExpression(self, ctx: vba_ccParser.NotOperatorExpressionContext): ...
    def visitConcatExpression(self, ctx: vba_ccParser.ConcatExpressionContext): ...
    def visitArithmeticExpression(self, ctx: vba_ccParser.ArithmeticExpressionContext): ...
    def visitBooleanExpression(self, ctx: vba_ccParser.BooleanExpressionContext): ...
    def visitIdentifierExpression(self, ctx: vba_ccParser.IdentifierExpressionContext): ...
    def visitLiteralExpression(self, ctx: vba_ccParser.LiteralExpressionContext): ...
    def visitCcFunc(self, ctx: vba_ccParser.CcFuncContext): ...
    def visitReservedKeywords(self, ctx: vba_ccParser.ReservedKeywordsContext): ...
